[project]
name = "trading-mcp-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.5.3",
    "fastmcp>=2.12.3",
    "loguru>=0.7.3",
    "mcp[cli]>=1.13.1",
]
